// ─── BIOME DEFINITIONS ────────────────────────────────────────────────────────

export const BIOMES = [
  {
    id: 'meadow',
    name: 'Meadow',
    capyPos: { x: 0, z: 0 },
    capyRotY: 0,
    orbitTarget: { x: 0, y: 0.5, z: 0 },
    cameraPos: { x: 3.5, y: 1.8, z: 4 },
    minDist: 3, maxDist: 12,
    minPolar: Math.PI / 4, maxPolar: Math.PI / 2.05,
    bg:             '#c8dce8',
    fogDensity:     0.014,
    skyTop:         '#87CEEB',
    skyBot:         '#d0ddd0',
    sunIntensity:   1.2,
    hemiSky:        '#d4e8f0',
    hemiGround:     '#3a5f2a',
    ambientIntensity: 0.4,
    companions: ['bee', 'rabbit'],
  },
  {
    id: 'riverside',
    name: 'Riverside',
    capyPos: { x: 2, z: -4 },
    capyRotY: -0.4,
    orbitTarget: { x: 2, y: 0.5, z: -4 },
    cameraPos: { x: 4, y: 1.8, z: 0 },
    minDist: 3, maxDist: 10,
    minPolar: Math.PI / 5, maxPolar: Math.PI / 2.05,
    bg:             '#a8c0d4',
    fogDensity:     0.016,
    skyTop:         '#7aaabf',
    skyBot:         '#b0c0be',
    sunIntensity:   0.9,
    hemiSky:        '#b8d0e0',
    hemiGround:     '#3a5040',
    ambientIntensity: 0.5,
    companions: ['firefly', 'frog'],
  },
  {
    id: 'jungle',
    name: 'Jungle',
    capyPos: { x: 0, z: -2 },
    capyRotY: 0,
    orbitTarget: { x: 0, y: 0.5, z: -2 },
    cameraPos: { x: 2.5, y: 1.8, z: 2 },
    minDist: 2, maxDist: 8,
    minPolar: Math.PI / 4, maxPolar: Math.PI / 2.05,
    bg:             '#7a9878',
    fogDensity:     0.022,
    skyTop:         '#4a7a60',
    skyBot:         '#5a7050',
    sunIntensity:   0.7,
    hemiSky:        '#a0c890',
    hemiGround:     '#2a4a20',
    ambientIntensity: 0.55,
    companions: ['bee', 'firefly'],
  },
  {
    id: 'mountain',
    name: 'Mountain Top',
    capyPos: { x: 0, z: 0 },
    capyRotY: 0,
    orbitTarget: { x: 0, y: 0.5, z: 0 },
    cameraPos: { x: 4, y: 2.5, z: 5 },
    minDist: 3, maxDist: 14,
    minPolar: Math.PI / 5, maxPolar: Math.PI / 2.1,
    bg:             '#b8cce0',
    fogDensity:     0.008,
    skyTop:         '#4a80cc',
    skyBot:         '#c0d4e8',
    sunIntensity:   1.4,
    hemiSky:        '#c0d8f0',
    hemiGround:     '#6a6460',
    ambientIntensity: 0.35,
    companions: ['eagle', 'rabbit'],
  },
  {
    id: 'snowy',
    name: 'Snowy Peak',
    capyPos: { x: 0, z: 0 },
    capyRotY: 0,
    orbitTarget: { x: 0, y: 0.5, z: 0 },
    cameraPos: { x: 3.5, y: 1.8, z: 4 },
    minDist: 3, maxDist: 12,
    minPolar: Math.PI / 4, maxPolar: Math.PI / 2.05,
    bg:             '#c8d8e8',
    fogDensity:     0.020,
    skyTop:         '#8aaac8',
    skyBot:         '#d8e4f0',
    sunIntensity:   0.8,
    hemiSky:        '#c0d0e4',
    hemiGround:     '#888898',
    ambientIntensity: 0.55,
    autoSnow:       true,   // enables snow particles on biome enter
    companions: ['rabbit', 'penguin'],
  },
  {
    id: 'lofi-desk',
    name: 'Lofi Desk',
    capyPos: { x: 0, z: 0 },
    capyRotY: 0,
    orbitTarget: { x: 0, y: 0.3, z: 0.4 },
    cameraPos: { x: 2.5, y: 1.2, z: 2.8 },
    minDist: 1.5, maxDist: 6,
    minPolar: Math.PI / 5, maxPolar: Math.PI / 2.1,
    bg:             '#c4a878',
    fogDensity:     0.003,
    skyTop:         '#c49060',
    skyBot:         '#e8c890',
    sunIntensity:   0.5,
    hemiSky:        '#e8c880',
    hemiGround:     '#604a30',
    ambientIntensity: 0.75,
    companions: ['laptop', 'headphones', 'sunglasses', 'lemonade'],
  },
];

// ─── COMPANION DEFINITIONS ─────────────────────────────────────────────────────

export const COMPANIONS = [
  {
    id: 'bee',
    name: 'Bee',
    emoji: '🐝',
    placementMode: 'hover_around',
    allowedBiomes: ['meadow', 'jungle'],
    preferTime: 'day',
    preferWeather: 'clear',
    hoverRadius: 1.6,
    hoverHeight: 1.7,
    hoverSpeed: 0.55,
    specialCombo: { biome: 'meadow', time: 'day', weather: 'clear' },
  },
  {
    id: 'firefly',
    name: 'Firefly',
    emoji: '✨',
    placementMode: 'hover_around',
    allowedBiomes: ['riverside', 'jungle'],
    preferTime: 'night',
    preferWeather: 'any',
    hoverRadius: 2.0,
    hoverHeight: 1.8,
    hoverSpeed: 0.38,
    specialCombo: { time: 'night' },
  },
  {
    id: 'frog',
    name: 'Frog',
    emoji: '🐸',
    placementMode: 'sit_on_capy',
    allowedBiomes: ['riverside'],
    preferTime: 'any',
    preferWeather: 'rain',
    sitAnchor: { x: 0, y: 0.95, z: -0.05 },
    specialCombo: { weather: 'rain', biome: 'riverside' },
  },
  {
    id: 'rabbit',
    name: 'Rabbit',
    emoji: '🐰',
    placementMode: 'sit_on_capy',
    allowedBiomes: ['meadow', 'mountain', 'snowy'],
    preferTime: 'day',
    preferWeather: 'clear',
    sitAnchor: { x: 0, y: 0.95, z: -0.05 },
    specialCombo: { biome: 'meadow', time: 'day' },
  },
  {
    id: 'eagle',
    name: 'Eagle',
    emoji: '🦅',
    placementMode: 'hover_around',
    allowedBiomes: ['mountain'],
    preferTime: 'day',
    preferWeather: 'clear',
    hoverRadius: 2.8,
    hoverHeight: 2.4,
    hoverSpeed: 0.28,
    specialCombo: { biome: 'mountain', time: 'day', weather: 'clear' },
  },
  {
    id: 'penguin',
    name: 'Penguin',
    emoji: '🐧',
    placementMode: 'sit_on_capy',
    allowedBiomes: ['snowy'],
    preferTime: 'any',
    preferWeather: 'any',
    sitAnchor: { x: 0, y: 0.92, z: -0.02 },
    specialCombo: { biome: 'snowy' },
  },
  {
    id: 'laptop',
    name: 'Laptop',
    emoji: '💻',
    placementMode: 'sit_on_capy',
    allowedBiomes: ['lofi-desk'],
    preferTime: 'night',
    preferWeather: 'any',
    sitAnchor: { x: 0, y: 0.02, z: 0.55 },
    specialCombo: { biome: 'lofi-desk', time: 'night' },
  },
  {
    id: 'headphones',
    name: 'Headphones',
    emoji: '🎧',
    placementMode: 'sit_on_capy',
    allowedBiomes: ['lofi-desk'],
    preferTime: 'any',
    preferWeather: 'any',
    sitAnchor: { x: 0, y: 1.28, z: 0.58 },
    specialCombo: { biome: 'lofi-desk' },
  },
  {
    id: 'sunglasses',
    name: 'Sunnies',
    emoji: '🕶️',
    placementMode: 'sit_on_capy',
    allowedBiomes: ['lofi-desk'],
    preferTime: 'day',
    preferWeather: 'clear',
    sitAnchor: { x: 0, y: 1.04, z: 0.82 },
    specialCombo: { biome: 'lofi-desk', time: 'day' },
  },
  {
    id: 'lemonade',
    name: 'Lemonade',
    emoji: '🍋',
    placementMode: 'sit_on_capy',
    allowedBiomes: ['lofi-desk'],
    preferTime: 'day',
    preferWeather: 'clear',
    sitAnchor: { x: 0.55, y: 0.02, z: 0.0 },
    specialCombo: { weather: 'clear', biome: 'lofi-desk' },
  },
];

// ─── SCORING ───────────────────────────────────────────────────────────────────
export const SCORING = {
  soloBase: 1,
  soloNightBonus: 2,
  soloRainBonus: 1,
  companionBase: 3,
  timeMatchBonus: 2,
  weatherMatchBonus: 2,
  specialComboBonus: 2,
  thresholds: { neutral: 0, good: 3, great: 6 },
};

// ─── NIGHT ATMOSPHERE ─────────────────────────────────────────────────────────
export const NIGHT = {
  bg:               '#0d1520',
  fogDensity:       0.025,
  skyTop:           '#080c18',
  skyBot:           '#14202e',
  sunIntensity:     0.05,
  moonIntensity:    0.25,
  ambientIntensity: 0.15,
  hemiSky:          '#1a2840',
  hemiGround:       '#0a1008',
};

export const RAIN_OVERLAY = {
  bgShift:     '#5a6268',
  fogAdd:      0.010,
  skyTopShift: '#505860',
  skyBotShift: '#788080',
  sunReduce:   0.8,
  ambientAdd:  0.15,
};
